### ISSUE TITLE
Feature Request: Assiciate treatments to samples/followup/primary_diagnoses

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-dictionary#85]
**We need to be able to answer the questions like this:**
Which tumour was this treatment related to?
Which sample was associated with this primary diagnosis?
Which diagnosis was this follow_up related to? 

## Implementation
- add `submitter_primary_diagnosis_id` on primary_diagnosis file
- add `submitter_primary_diagnosis_id` on specimen file
- add `submitter_primary_diagnosis_id` on treatment file
- add `submitter_primary_diagnosis_id` on follow_up file
- add `submitter_treatment_id` on follow_up file (optional)

## Noted for clinical 
For this dictionary change we will have some dependencies on clinical:
- Make sure there can be multiple primary_diagnosis entities

**Comment by rosibaj** [comment]
one outstanding question: 
- sometimes patients are given neoadjuvant treatment before they are diagnosed. So I'm 
- not sure if a value for `submitter_primary_diagnosis_id` in the `Treatment` table can be submitted (or maybe we need a validation script). 
- Before we move ahead with this change, confirm this with someone in the working group first.

will be confirmed by @hknahal on Thursday

**Comment by hknahal** [comment]
Had discussions with working group about this. Treatment is always based on the initial primary diagnosis, so it makes sense to have `submitter_primary_diagnosis_id` in the treatment file. You  need knowledge about the primary diagnosis in order to administer any treatment, including  neoadjuvant treatment.  

Response from working group: "_**A neoadjuvant treatment is based on an initial (primary) diagnosis**. The diagnosis after surgery is a diagnosis on the **primary tumor,** but not the primary diagnosis. We already named it “initial” to avoid misunderstandings._"

**Comment by rosibaj** [comment]
https://github.com/icgc-argo/argo-dictionary/pull/93

**Comment by kcullion** [comment]
@rosibaj tested, and these ids have been added both in the files for the platform (v47.00) and in your latest netlify link. I'll let you move this ticket accordingly
